accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
    path('signup/', views.signup, name="signup"),
    path('<username>/', views.index, name='index'),
]

instagram/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('explore/', views.index, name='index'),
    path('posts/<int:post_pk>/', views.detail, name='detail'),
    path('posts/new/', views.create, name='create'),
    # path('posts/<int:post_pk>/comments', views.comment_create, name='comment_create'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={"post_pk": self.pk})
    
    
class Image(models.Model):
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    class Meta:
        order_with_respect_to = 'post'

class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Image

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']

class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ['image']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'multiple': ''})
        
    def save(self, *args, **kwargs):
        # print(self.fields.get('image'))
    
        # file_list = self.fields.get('image')
        # print(dir(file_list))
        # for file in file_list.values():
        # Image.objects.create(image=file, post=kwargs.get('post'))
        return super().save(*args, **kwargs)

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup(request):
    if request.method=="POST":
        account_form = UserCreationForm(request.POST)
        if account_form.is_valid():
            user = account_form.save()
            login(request, user)
            return redirect('posts:index')
        
    else: 
        account_form = UserCreationForm()
    context = {'account_form': account_form}
    return render(request,'accounts/form.html', context)

def signout(request):
    logout(request)
    return redirect('posts:index')

def signin(request):
        if request.user.is_authenticated:
            return redirect('posts:index')
        if request.method == "POST": 
            account_form =  AuthenticationForm(request, request.POST)
            if account_form.is_valid():
                login(request, account_form.get_user())
                return redirect('posts:index')
        else:
            account_form = AuthenticationForm()
        context = {'account_form': account_form}
        return render(request,'accounts/form.html', context)

@login_required
def index(request, username):
    User = get_user_model()
    user = get_object_or_404(User, username=username)
    posts = user.post_set.order_by('-pk')
    context = {'user': user, 'posts': posts}
    return render(request, 'posts/index.html', context)

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Post, Image
from .forms import PostForm, ImageForm
# Create your views here.
def index(request):
    posts = Post.objects.order_by('-pk')
    context = {'posts': posts}
    return render(request, 'posts/index.html', context)

def detail(request, post_pk):
    post = get_object_or_404(Post.objects.prefetch_related('image_set'), pk=post_pk)
    images = post.image_set.all()
    context = {'post': post, 'images': images}
    return render(request, 'posts/detail.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        # print(request.FILES)
        # print(request.FILES.get)
        post_form = PostForm(request.POST)
        image_form = ImageForm(request.FILES)
        print(request.FILES)
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            for image in request.FILES.getlist('image'):            
                Image.objects.create(image=image, post=post)
            # post.image_set.add()
            return redirect(post)
    else:
        post_form = PostForm()
        image_form = ImageForm()
    context = {'post_form': post_form, 'image_form': image_form}
    return render(request, 'posts/form.html', context)

# def comment_create(request, post_pk):
#     post = get_object_or_404(Post.objects.prefetch_related('image_set'), pk=post_pk)
#     if request.method == 'POST':
#         # print(request.FILES)
#         # print(request.FILES.get)
#         comment_form = CommentForm(request.POST)
#         if comment_form .is_valid():
#             comment = comment_form.save(commit=False)
#             comment.post = post
#             comment.save()
#             return redirect(post)
#     else:
#         comment_form = CommentForm()
#     return redirect(post)

accounts/templates/accounts/form.html
{% extends "posts/base.html" %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ account_form.as_p }}
        <input type="submit" value="Submit"/>
    </form>
    <p><a href="{% url 'password_reset' %}">Lost password?</a></p>
{% endblock %}

accounts/templates/accounts/index.html
{% extends "posts/base.html" %}
{% block body %}

{% endblock %}

posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Instagram</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block css %}
    {% endblock %}
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

posts/templates/posts/detail.html
{% extends 'posts/base.html' %}
{% block css %}
<style>
    .card-content {
        height: 300px;
        line-height: 300px;
    }
</style>
{% endblock %}
{% block body %}
<div class="mt-5">
    <div id="post" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="row">
            <div class="col-8">
                <div class="carousel-inner">
                    {% for image in images %}
                    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                        <img src="{{ image.image.url }}" class="d-block w-100" alt="...">
                    </div>
                    {% endfor %}
                    <a class="carousel-control-prev" href="#post" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#post" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-4">
                <div id="post_content">
                    <h2>{{ user.username }}</h2>
                    <hr>
                    <p>{{ post.content }}</p>
                    <hr>
                    <p class="text-secondary">{{ post.created_at }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

posts/templates/posts/form.html
{% extends 'posts/base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ post_form.as_p }}
    {{ image_form.as_p }}
    <input type="submit">
</form>
{% endblock %}

posts/templates/posts/index.html
{% extends 'posts/base.html' %}
{% block body %}
{% if user.is_authenticated %}
    <a href="{% url 'accounts:signout' %}">로그아웃</a>
{% else %}
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    <a href="{% url 'accounts:signin' %}">로그인</a>
{% endif %}
<a href="{% url 'posts:create' %}">새 글 쓰기</a>
<div class="row mt-5">
    {% for post in posts %}
    <div class="col-4">
        <div class="card">
            <a href="{{ post.get_absolute_url }}"><img src="{{post.image_set.first.image.url}}" class="img-fluid"></a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}